# Generated by Django 3.2.6 on 2021-08-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdeal', '0002_mydeal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydeal',
            name='enroll',
            field=models.CharField(default='', max_length=200),
        ),
    ]
